version: "3"

services:
    node:
        container_name: api
        restart: always
        build: ./
        env_file:
            - ./config/dev.env
        ports:
            - 3000:3000
        volumes:
            - .:/app
        depends_on:
            - mongo

    mongo:
        container_name: db
        image: mongo
        ports:
            - 27017:27017
